---
# Ansible playbook for attackbox provisioning
- name: "Provision Kali Linux attackbox"
  hosts: attackbox
  become: yes
  tasks:
    - name: "Enable SSH service"
      systemd:
        name: ssh
        enabled: yes
        state: started

    - name: "Configure SSH to allow password authentication"
      lineinfile:
        path: /etc/ssh/sshd_config
        regexp: '^#?PasswordAuthentication'
        line: 'PasswordAuthentication yes'
        state: present
      notify: restart ssh

    - name: "Set kali user password"
      user:
        name: kali
        password: "{{ 'kali' | password_hash('sha512') }}"
        state: present

    - name: "Add kali user to sudo group"
      user:
        name: kali
        groups: sudo
        append: yes

    - name: Set zsh as default shell for kali user
      user:
        name: kali
        shell: /usr/bin/zsh

    - name: "Install uv"
      shell: |
        curl -LsSf https://astral.sh/uv/install.sh | sh

    - name: "Install nodejs, npm and Caldera prereqs"
      apt:
          name:
          - nodejs
          - npm
          - git
          - zlib1g
          - tmux
          state: present
          update_cache: yes

    - name: "Download Caldera from git"
      shell:
        cd /home/kali && git clone https://github.com/mitre/caldera.git --recursive --tag 5.3.0

    - name: "Change 'lxml~=4.9.0  # debrief' to 'lxml~=5.3.0  # debrief' in requirements.txt"
      replace:
        path: /home/kali/5.3.0/requirements.txt
        regexp: 'lxml~=4.9.0'
        replace: 'lxml~=5.3.0'

    - name: "Change 'lxml~=4.9.0  # debrief' to 'lxml~=5.3.0  # debrief' in plugins/stockpile/requirements.txt"
      replace:
        path: /home/kali/5.3.0/plugins/stockpile/requirements.txt
        regexp: 'lxml~=4.9.0'
        replace: 'lxml~=5.3.0'

    - name: "Install Caldera"
      shell: |
        cd /home/kali/5.3.0 && uv venv && uv pip install -r requirements.txt && uv pip install -r plugins/stockpile/requirements.txt

    - name: "Start Caldera in a tmux session"
      shell: |
        cd /home/kali/5.3.0 && tmux new-session -d -s caldera 'uv run server.py --insecure --build --fresh'

  handlers:
    - name: restart ssh
      systemd:
        name: ssh
        state: restarted
