#Aleem Ladha @LadhaAleem
#Credits to SOCFortress and Mayfly277
- name: Install and configure Wazuh Manager
  hosts: wazuh_server
  become: yes
  roles:
    - { role: 'wazuh_manager', tags: 'wazuh_manager' }
  tasks:
    - name: Disable vulnerability-detection in ossec.conf
      shell:
        sed -i '/<vulnerability-detection>/,/<\/vulnerability-detection>/d' /var/ossec/etc/ossec.conf
    - name: Add vulnerability-detection section set to no in ossec.conf
      blockinfile:
        path: /var/ossec/etc/ossec.conf
        insertafter: '<ossec_config>'
        block: |
            <vulnerability-detection>
                <enabled>no</enabled>
            </vulnerability-detection>
        marker: "<!-- {mark} ANSIBLE MANAGED BLOCK -->"
        state: present

- name: Preconfigure Wazuh Agent Machines
  hosts: wazuh_agents
  tasks:
    - name: Install windows defender
      win_feature:
        name: Windows-Defender
      register: win_defender_install

    - name: Reboot if needed
      win_reboot:
        reboot_timeout: 600
        post_reboot_delay: 30
      when: win_defender_install.reboot_required

    - name: Disable windows defender sending sample
      win_shell: Set-MpPreference -MAPSReporting 0

    - name: Disable windows defender sending sample
      win_shell: Set-MpPreference -SubmitSamplesConsent 2

    - name: Disable network drive scanning
      win_shell: Set-MpPreference -DisableScanningMappedNetworkDrivesForFullScan $true

    - name: Enable realtime monitoring
      win_shell: Set-MpPreference -DisableRealtimeMonitoring $false
  roles:
    - { role: 'logs_windows', tags: 'agent' }

- name: Install Wazuh Agent
  hosts: wazuh_agents
  roles:
    - { role: 'wazuh_agent', tags: 'wazuh_agent' }
  tasks:
    - name: Add MSDefender and Sysmon collection rules to agent ossec.conf
      randrej.windows.win_blockinfile:
        path: 'C:\Program Files (x86)\ossec-agent\ossec.conf'
        insertafter: '<ossec_config>'
        block: |
          <!-- Chainsaw Sigma Integration -->
          <wodle name="command">
            <disabled>no</disabled>
            <tag>windows_chainsaw</tag>
            <command>powershell.exe -executionpolicy bypass -File "C:\Program Files\socfortress\chainsaw.ps1"</command>
            <interval>1m</interval>
            <ignore_output>yes</ignore_output>
            <run_on_start>yes</run_on_start>
            <timeout>0</timeout>
          </wodle>
          <!-- Microsoft Defender Logs -->
          <localfile>
            <location>Microsoft-Windows-Windows Defender/Operational</location>
            <log_format>eventchannel</log_format>
          </localfile>
          <!-- Sysmon Logs -->
          <localfile>
            <location>Microsoft-Windows-Sysmon/Operational</location>
            <log_format>eventchannel</log_format>
          </localfile>
        marker: "<!-- {mark} ANSIBLE MANAGED BLOCK -->"
        state: present

    - name: Restart Wazuh Agent service to apply configuration changes
      win_service:
        name: WazuhSvc
        state: restarted

  vars:
    wazuh_manager_host: "{{ hostvars['wazuh']['ansible_host'] }}"

- name: Install Wazuh Agent
  hosts: wazuh_agents_linux
  become: yes
  roles:
    - { role: 'wazuh_agent_linux', tags: 'wazuh_agent_linux' }
  vars:
    wazuh_manager_host: "{{ hostvars['wazuh']['ansible_host'] }}"
