# use /opt/wazuh instead of /tmp to keep track
- name: Create /opt/wazuh directory if it does not exist
  ansible.builtin.file:
    path: /opt/wazuh
    state: directory
    mode: '0755'

# check existence to not reinstall if already installed
- name: Check services facts
  ansible.builtin.service_facts:

# - name: Print service facts
#   ansible.builtin.debug:
#     var: ansible_facts.services

- name: Download Wazuh installation script
  get_url:
    url: "{{ wazuh_install_script_url }}"
    dest: /opt/wazuh/wazuh-install.sh
  when: not ansible_facts.services['wazuh-manager.service'] is defined

- name: Run Wazuh installation script
  shell: |
    sudo bash /opt/wazuh/wazuh-install.sh -a -i > /opt/wazuh/wazuh-install-output.txt
  when: not ansible_facts.services['wazuh-manager.service'] is defined

# FIX false positive on  /bin/diff  cf. https://github.com/wazuh/wazuh/issues/19000
- name: fix rootkit trojan detection due to issue
  ansible.builtin.lineinfile:
    path: /var/ossec/etc/rootcheck/rootkit_trojans.txt
    search_string: 'diff        !bash|^/bin/sh|file\.h|proc\.h|/dev/[^n]|^/bin/.*sh!'
    line: 'diff        !bash|^/bin/sh|file\.h|proc\.h|/dev/[^nf]|^/bin/.*sh!'

- name: Start Wazuh Manager service
  service:
    name: wazuh-manager
    state: started
    enabled: yes

- name: Run SOCFORTRESS Wazuh rules script
  shell: |
    wget -q ~/wazuh_socfortress_rules.sh https://raw.githubusercontent.com/socfortress/Wazuh-Rules/main/wazuh_socfortress_rules.sh
    sudo chmod +x wazuh_socfortress_rules.sh
    yes | sudo bash ./wazuh_socfortress_rules.sh

- name: Extract username and password
  shell: "grep -E 'User:|Password:' /opt/wazuh/wazuh-install-output.txt | awk '{print $NF}'"
  register: access_info

- name: Extract wazuh-install-files.tar
  ansible.builtin.unarchive:
    src: /opt/wazuh/wazuh-install-files.tar
    dest: /opt/wazuh/
    remote_src: yes
    creates: /opt/wazuh/wazuh-install-files/wazuh-passwords.txt

- name: Read wazuh-passwords.txt
  ansible.builtin.slurp:
    src: /opt/wazuh/wazuh-install-files/wazuh-passwords.txt
  register: wazuh_passwords_content

- name: Extract Wazuh API credentials
  ansible.builtin.set_fact:
    wazuh_api_username: "{{ wazuh_passwords_content.content | b64decode | regex_search('# Password for wazuh API user\\s+api_username:\\s+[\\'\"](\\w+)[\\'\"]', '\\1') | first }}"
    wazuh_api_password: "{{ wazuh_passwords_content.content | b64decode | regex_search('# Password for wazuh API user\\s+api_username:\\s+[\\'\"]\\w+[\\'\"]\\s+api_password:\\s+[\\'\"](.*?)[\\'\"]', '\\1') | first }}"
    wazuh_wui_api_username: "{{ wazuh_passwords_content.content | b64decode | regex_search('# Password for wazuh-wui API user\\s+api_username:\\s+[\\'\"](\\w+-?\\w+)[\\'\"]', '\\1') | first }}"
    wazuh_wui_api_password: "{{ wazuh_passwords_content.content | b64decode | regex_search('# Password for wazuh-wui API user\\s+api_username:\\s+[\\'\"]\\w+-?\\w+[\\'\"]\\s+api_password:\\s+[\\'\"](.*?)[\\'\"]', '\\1') | first }}"

- name: Display username and password
  debug:
    msg:
      - "Username: {{ access_info.stdout_lines[0] }}"
      - "Password: {{ access_info.stdout_lines[1] }}"

- name: Display Wazuh API credentials
  debug:
    msg:
      - "Wazuh API Username: {{ wazuh_api_username }}"
      - "Wazuh API Password: {{ wazuh_api_password }}"
      - "Wazuh-WUI API Username: {{ wazuh_wui_api_username }}"
      - "Wazuh-WUI API Password: {{ wazuh_wui_api_password }}"

