#- name: Install winlogbeat
#  import_tasks: winlogbeat.yml
#
#- name: Set winlogbeat config file
#  win_copy:
#    src: winlogbeat.yml
#    dest: C:\ProgramData\chocolatey\lib\winlogbeat\tools\

# sysmon install (https://github.com/NVISOsecurity/ansible-sysmon)
- name: Create directory
  win_file:
    path: "{{ sysmon_install_location }}"
    state: directory
  register: result

- name: Get sysmon zip
  win_copy:
    src: "{{ sysmon_download_file }}{{ file_ext }}"
    dest: "{{ sysmon_install_location }}/{{ sysmon_download_file }}{{ file_ext }}"

- name: Unzip sysmon
  win_unzip:
    src: "{{ sysmon_install_location }}/{{ sysmon_download_file }}{{ file_ext }}"
    dest: "{{ sysmon_install_location }}"

- name: Copy sysmon config
  win_copy:
    src: sysmonconfig-export.xml
    dest: c:\sysmon\sysmonconfig-export.xml

- name: Uninstall sysmon if already installed
  win_command: "{{ sysmon_install_location }}\\sysmon64.exe -u"
  args:
    chdir: "{{ sysmon_install_location }}"
  ignore_errors: yes

- name: Run sysmon
  win_command: "{{ sysmon_install_location }}\\sysmon64.exe -accepteula -i {{ sysmon_install_location }}\\sysmonconfig-export.xml"
  args:
    chdir: "{{ sysmon_install_location }}"

- name: Create directory for socfortress
  win_file:
    path: C:\\Program Files\\socfortress
    state: directory

- name: Copy chainsaw zip file
  win_copy:
    src: chainsaw.zip
    dest: C:\\Program Files\\socfortress\\chainsaw.zip

- name: Unzip chainsaw
  win_unzip:
    src: C:\\Program Files\\socfortress\\chainsaw.zip
    dest: C:\\Program Files\\socfortress
    remote_src: yes

- name: Create directory for sigma
  win_file:
    path: C:\\Program Files\\socfortress\\chainsaw\\sigma
    state: directory

- name: Copy sigma rules
  win_copy:
    src: sigma_core.zip
    dest: C:\\Program Files\\socfortress\\chainsaw\\sigma\\sigma_core.zip

- name: Unzip sigma rules
  win_unzip:
    src: C:\\Program Files\\socfortress\\chainsaw\\sigma\\sigma_core.zip
    dest: C:\\Program Files\\socfortress\\chainsaw\\sigma
    remote_src: yes

- name: Copy visual C++ redistributable
  win_copy:
    src: VC_redist.x64.exe
    dest: C:\\tmp\\vc_redist.x64.exe

- name: Install visual C++ redistributable
  ansible.windows.win_package:
    path: C:\\tmp\\vc_redist.x64.exe
    arguments: /install /quiet /norestart

- name: Copy chainsaw.ps1
  win_copy:
      src: chainsaw.ps1
      dest: C:\\Program Files\\socfortress\\chainsaw.ps1

# RUN winlogbeat
#- name: check winlogbeat service
#  win_service:
#    name: winlogbeat
#  register: resultwlb
#  failed_when: resultwlb is not defined
#  ignore_errors: yes
#
#- name: Reboot before launch setup
#  win_reboot:
#    reboot_timeout: 600
#    post_reboot_delay: 100
#  when: resultwlb.state is defined and resultwlb.state != 'running'
#
#- name: Run winlogbeat setup
#  win_command: "winlogbeat setup -e"
#  args:
#    chdir: "{{ winlogbeat_service.install_path_64 }}\\winlogbeat-{{ winlogbeat_service.version }}-windows-x86_64\\"
#  when: resultwlb.state is defined and resultwlb.state != 'running'
#
## RUN winlogbeat
#- name: check winlogbeat service
#  win_service:
#    name: winlogbeat
#    start_mode: auto
#    state: started
#  when: resultwlb.state is defined and resultwlb.state != 'running'